[project]
name = "reinforcement-learning-gymnasium"
version = "0.1.0"
description = "Q-Learning agent in Grid World using Gymnasium"
requires-python = ">=3.10"
dependencies = [
    "gymnasium>=0.29.1",
    "numpy>=1.24.0",
    "matplotlib>=3.7.0",
]
